export const LINE_GAP = 2,
    WIDTH = 1200,
    HEIGHT = 800,
    ITEM_HEIGHT = 150,
    ITEM_WIDTH = 200,
    GROUP_COMPONENT_HEIGHT = 20,
    RHG_ID = '_ID',
    DEBOUNCE_SCROLLING = 50,
    DEBOUNCE_FILTERING = 50,
    NO_FILTER_DATA_MESSAGE = 'no data',
    UNGROUPED = '__UNGROUPED__',
    FILTERS = {
        ALL : 'ALL',
        GLOBAL : 'GLOBAL',
        FIELDS : 'FIELDS',
    };
